version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/websites/conf:/etc/nginx/conf.d
      - /var/websites/vhost:/etc/nginx/vhost.d
      - /var/websites/html:/usr/share/nginx/html
      - /var/websites/certs:/etc/nginx/certs:ro
      - /var/websites/acme.sh:/etc/acme.sh
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes:
      - /var/websites/vhost:/etc/nginx/vhost.d
      - /var/websites/html:/usr/share/nginx/html
      - /var/websites/certs:/etc/nginx/certs
      - /var/websites/acme.sh:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always