version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always

volumes:
  conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/var/websites/conf"
  vhost:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/var/websites/vhost"
  html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/var/websites/html"
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/var/websites/certs"
  acme:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/var/websites/acme"